spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Gamza?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: gamza
    password: gamza@

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
    freemarker:
      cache: false
    jackson:
      serialization:
        fail-on-empty-beans: false

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
  sql:
    init:
      mode: always

    logging:
      level:
        org.hibernate.SQL: debug


jwt:
  secret: 3a696b633a22fab4f16485961e65fd6bd91d7a708faa4bbca918afefed0818e0

kakao:
  restApiKey: b8201d590e870a0295523da6db288aee
  redirectURI: http://localhost:8080/auth/login/kakao




